export enum TransportType {
    plane = "plane",
    bus = "bus",
    boat = "boat",
    car = "car",
    fossilFueledCar = "fossil Fueled Car",
    electricVehicle = "electric Vehicle",
    hybridCar = "hybrid Car",
    carSharing = "car Sharing",
    motorbike = "motorbike",
    shortDistanceBus = "short Distance Bus",
    longDistanceBus = "long Distance Bus",
    train = "train",
    shortHaulFlight = "short Haul Flight",
    mediumHaulFlight = "medium Haul Flight",
    longHaulFlight = "long Haul Flight",
}
